vich_uploader:
    db_driver: orm

    mappings:
       media_object:
            uri_prefix: /images/annonces
            upload_destination: '%kernel.project_dir%/public/images/annonces'
            namer: Vich\UploaderBundle\Naming\OrignameNamer
